networks:
  mongo-network:
    driver: bridge

volumes:
  mongo-data:

services:
  mongo-cluster:
    image: mongo
    container_name: mongo-cluster
    hostname: mongo-cluster
    entrypoint: >
      /bin/bash -c '
      openssl rand -base64 756 > /data/keyfile.key &&
      chmod 400 /data/keyfile.key &&
      chown mongodb:mongodb /data/keyfile.key &&
      /usr/local/bin/docker-entrypoint.sh mongod --keyFile /data/keyfile.key --bind_ip_all'

    ports:
      - "${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    healthcheck:
      test: mongosh
        -u $${MONGO_INITDB_ROOT_USERNAME}
        -p $${MONGO_INITDB_ROOT_PASSWORD}
        --eval "try { rs.status() } catch (err) { print(err) }" | mongosh --port ${MONGO_INITDB_PORT} --quiet
      interval: 10s
      timeout: 10s
      retries: 5
