type HTTP_STATUS =
  | "STATUS_OK"
  | "STATUS_CREATED"
  | "STATUS_NO_CONTENT"
  | "STATUS_BAD_REQUEST"
  | "STATUS_UNAUTHORIZED"
  | "STATUS_FORBIDDEN"
  | "STATUS_NOT_FOUND"
  | "STATUS_CONFLICT"
  | "STATUS_INTERNAL_SERVER_ERROR"
  | "STATUS_SERVICE_UNAVAILABLE"
  | "STATUS_TOO_MANY_REQUESTS"
  | "STATUS_UNPROCESSABLE_ENTITY";

export const HTTP_STATUS_CODE: Record<HTTP_STATUS, number> = {
  STATUS_OK: 200,
  STATUS_CREATED: 201,
  STATUS_NO_CONTENT: 204,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_FORBIDDEN: 403,
  STATUS_NOT_FOUND: 404,
  STATUS_CONFLICT: 409,
  STATUS_TOO_MANY_REQUESTS: 429,
  STATUS_INTERNAL_SERVER_ERROR: 500,
  STATUS_SERVICE_UNAVAILABLE: 503,
  STATUS_UNPROCESSABLE_ENTITY: 422,
};
